VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsVegaForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

' This class will have functions to access the menu
' and other parts of the Main Vega Form from modules
' Experimental: Havent decided on final
' inclusion or not.

Public Sub AddMenu()
' Add a new menu item to the Vega Form's menu

End Sub


Public Sub AddButton()
' Add a new button to the form

End Sub
